app:
  build: "."
  dockerfile: "dockerfile.app"
  ports:
    - "3000:3000"
  links:
    - "db"
  volumes:
    - ".:/var/www/verbose-api"
  env_file:
    - "env.development"

db:
  build: "."
  dockerfile: "dockerfile.db"
